---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  selector:
    deployment=hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
